apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
  labels:
    app: student-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      imagePullSecrets:
        - name: acr-auth
      containers:
        - name: student-app
          image: dummy/dummy:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "mysqlserverforproject.mysql.database.azure.com"
            - name: DB_USER
              value: "adminuser"
            - name: DB_PASSWORD
              value: "8888Kush@l"
            - name: DB_NAME
              value: "studentdb"
